device: cuda
batch_size: 128

# Dataset Path
datasets:
  dataset_type: gnn
  train_path: "/nethome/sye40/PrisonerEscape/datasets/train/gnn_map_0_run_300_eps_0.1_norm_random_cameras"
  test_path: "/nethome/sye40/PrisonerEscape/datasets/test/gnn_map_0_run_100_eps_0.1_norm_random_cameras"
  view: blue # only for blue view
  seq_len: 16

  # Multistep into the future
  multi_head: True
  num_heads: 1
  step_length: 30
  include_current: False

  # Options for different node features
  one_hot_agents: True
  detected_location: False
  timestep: False

# Model Setup
model:
  model_type: 'gnn'
  load_pth: null
  input_dim: 254
  encoder_type: 'lstm'
  hidden_dim: 8
  gnn_hidden_dim: 8
  decoder_type: 'mixture'
  number_gaussians: 4

# Training Setup
training:
  log_dir: "logs/gnn/prediction"  
  seed: 104
  learning_rate: 0.001
  epochs: 120
  l2_lambda: 0
  ml_flow_experiment: 4