language: python

python:
  - "3.7"
  - "3.8" # Currently developing python

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  python demo/test.py
  #- pytest
