device: cuda
batch_size: 128

# Dataset Path
datasets:
  dataset_type: vector
  train_path: "/nethome/sye40/PrisonerEscape/datasets/post_red_obs_fix/map_0_400_RRT_gnn_save.npz"
  test_path: "/nethome/sye40/PrisonerEscape/datasets/post_red_obs_fix/map_0_run_100_rrt.npz"
  # test_path: "/nethome/sye40/PrisonerEscape/datasets/post_red_obs_fix/map_0_100_gnn_save.npz"
  view: blue # only for blue view
  seq_len: 16
  num_workers: 4

  # Multistep into the future
  multi_head: True
  num_heads: 1
  step_length: 5
  include_current: False

# Model Setup
model:
  model_type: 'gmm_cvae'
  load_pth: null
  input_dim: 254
  encoder_hidden_dim: 16
  z_dim: 8
  future_hidden_dim: 16
  decoder_type: 'mixture'
  number_gaussians: 5
  gmm_bool: True

# Training Setup
training:
  save_epoch: False
  weight_decay: 0.0001
  scheduler: null
  log_dir: "/star-data/sye40/logs/gmm_cvae"  
  seed: 104
  learning_rate: 0.001
  epochs: 130
  l2_lambda: 0
  ml_flow_experiment: 10