device: cuda:1
batch_size: 128 

# Dataset Path
datasets:
  dataset_type: baseline
  train_path: "/nethome/sye40/PrisonerEscape/datasets/seed_corrected/map_0_run_300_eps_0.1_norm.npz"
  test_path: "/nethome/sye40/PrisonerEscape/datasets/seed_corrected/map_0_run_100_eps_0.1_norm.npz"
  # train_path: "/nethome/sye40/PrisonerClean/datasets/eps_0/map_0_run_300_eps_0_normalized.npz"
  # test_path: "/nethome/sye40/PrisonerClean/datasets/eps_0/map_0_run_100_eps_0_normalized.npz"
  input_obs: blue
  num_heads: 12
  seq_len: 16
  step_length: 5
  current_step: False

  future_step: 30

# Model Setup
model:
  load_pth: null
  model_type: 'unconnected'
  input_dim: 254
  encoder_type: 'lstm'
  hidden_dim: 64
  decoder_type: 'mixture'
  number_gaussians: 4

# Training Setup
training:
  log_dir: "logs/prediction"  
  seed: 102
  learning_rate: 0.001
  epochs: 200
  l2_lambda: 0.15