device: cuda
batch_size: 128 

# Dataset Path
datasets:
  train_path: "/nethome/sye40/PrisonerClean/datasets/eps_0/map_0_run_300_eps_0_normalized.npz"
  test_path: "/nethome/sye40/PrisonerClean/datasets/eps_0/map_0_run_100_eps_0_normalized.npz"
  input_obs: blue
  num_heads: 1
  seq_len: 16
  step_length: 0

# Model Setup
model:
  model_type: 'not_connected'
  input_dim: 254
  encoder_type: 'lstm'
  hidden_dim: 64
  decoder_type: 'mixture'
  number_gaussians: 4

# Training Setup
training:
  log_dir: "logs/filtering"  
  seed: 102
  learning_rate: 0.001
  epochs: 100
  l2_lambda: 0.1