seed: 0
epsilon: 0.0
heuristic_type: Normal

terrain: null
spawn_mode: uniform # uniform_hideout_dist
min_distance_from_hideout_to_start: 1000
random_cameras: False
camera_file_path: simulator/camera_locations/original_no_camera_net.txt
mountain_locations:
  - 400, 300
  - 1600, 1800
camera_range_factor: 1.0
observation_terrain_feature: False
random_hideout_locations: False
num_known_hideouts: 1
num_unknown_hideouts: 2
spawn_range: 350
max_timesteps: 4320
helicopter_battery_life: 200
helicopter_recharge_time: 40
num_search_parties: 5
terrain_map: simulator/forest_coverage/map_set/0.npy
step_reset: True
camera_net_bool: True
include_camera_at_start: False
include_start_location_blue_obs: True
store_last_k_fugitive_detections: False
num_random_known_cameras: 25
num_random_unknown_cameras: 25
known_hideout_locations: 
  - 2077, 2151
  - 2170, 603
  - 37, 1293
  - 1890, 30
  - 1151, 2369 
  - 356, 78 
  - 1751, 1433 
  - 1638, 1028 
  - 1482, 387 
  - 457, 1221
unknown_hideout_locations: 
  - 2077, 2151
  - 2170, 603
  - 37, 1293
  - 1890, 30
  - 1151, 2369
  - 356, 78
  - 1751, 1433
  - 1638, 1028
  - 1482, 387
  - 457, 1221