seed: 0
epsilon: 0.0
heuristic_type: Normal

terrain: null
spawn_mode: normal # uniform_hideout_dist
min_distance_from_hideout_to_start: 1000
random_cameras: False
camera_file_path: simulator/camera_locations/original_no_camera_net.txt
mountain_locations:
  - 400, 300
  - 1600, 1800
camera_range_factor: 1.0
observation_terrain_feature: False
random_hideout_locations: False
num_known_hideouts: 1
num_unknown_hideouts: 2
spawn_range: 350
max_timesteps: 500
helicopter_battery_life: 200
helicopter_recharge_time: 40
num_search_parties: 5
terrain_map: simulator/forest_coverage/map_set/0.npy
step_reset: True
camera_net_bool: True
include_camera_at_start: False
include_start_location_blue_obs: True
num_random_known_cameras: 25
num_random_unknown_cameras: 25
known_hideout_locations: 
  - 457, 1221
unknown_hideout_locations: 
  - 356, 78 
  - 1482, 387 
