FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

RUN pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cu113.html
RUN pip install matplotlib==3.5.2
RUN pip install tensorboard==2.9.1
RUN pip install torch-geometric==2.0.4
RUN pip install torch-geometric-temporal==0.52.0
RUN pip install dgl==0.6.1
RUN pip install mlflow==1.26.1

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install opencv-python