device: cuda
batch_size: 128

# Dataset Path
datasets:
  dataset_type: het_gnn

  train_path: "/workspace/star-data/random_start_locations/train"
  test_path: "/workspace/star-data/random_start_locations/test"

  # train_path: "/workspace/star-data/random_start_locations/dummy"
  # test_path: "/workspace/star-data/random_start_locations/dummy"
  view: blue # only for blue view
  seq_len: 16
  num_workers: 4

  # Multistep into the future
  multi_head: True
  num_heads: 12
  step_length: 5
  include_current: True

  # Options for different node features
  one_hot_agents: True
  detected_location: True
  timestep: True

  get_start_location: True

# Model Setup
model:
  model_type: hetero_gnn_lstm_front
  load_pth: null
  input_dim: 254
  encoder_type: 'lstm'
  hidden_dim: 8
  gnn_hidden_dim: 16
  decoder_type: 'mixture'
  number_gaussians: 4

# Training Setup
training:
  weight_decay: 0.0001
  scheduler: null
  log_dir: "logs/random_start/hetero_gnn" 
  seed: 104
  learning_rate: 0.001
  epochs: 130
  l2_lambda: 0
  ml_flow_experiment: 8