seed: 110

# Sequence type
outer_seq: 3
inner_seq: 16

# Decoder type
# decoder: SingleParam # Single vs Mixture
decoder: SingleStd #SingleStd, SingleParam, Mixture
reconstruction: Full #Full vs null
output_dim: 2
num_gaussians: 1

# dreamer model settings
obs_type: "red" # red is currently 113, blue is 254
in_dim: 25
learning_rate: 0.0003 
epochs: 35
hidden_dim: 64
embed_dim: 32
stoch_dim: 32
deter_dim: 128
loss_kl_weight: 2
stoch_discrete: 32
hidden_dim: 1000
gru_layers: 1
gru_type: 'gru'
layer_norm: False

# Training details
batch_size: 64
seq_len: 16
kl_balancing: 0.8
learning_rate: 0.001
min_decoder_loss: -3
# train_dataset_path: "/nethome/sye40/PrisonerEscape/shared_latent/dataset/map_0_run_300_eps_0.npz"
# test_dataset_path: "/nethome/sye40/PrisonerEscape/shared_latent/dataset/map_0_run_100_eps_0.npz"
train_dataset_path: "/nethome/sye40/PrisonerEscape/datasets/post_red_obs_fix/map_0_run_300_heuristic_eps_0.1.npz"
test_dataset_path: "/nethome/sye40/PrisonerEscape/datasets/post_red_obs_fix/map_0_run_100_heuristic_eps_0.1.npz"