device: cuda
batch_size: 128 

# Dataset Path
datasets:
  train_path: "/nethome/sye40/PrisonerClean/datasets/map_0_run_100_eps_0.1_norm.npz"
  test_path: "/nethome/sye40/PrisonerClean/datasets/map_0_run_100_eps_0.1_norm_test.npz"
  input_obs: red
  step_length: 5
  seq_len: 16
  num_heads: 12

# Model Setup
model:
  input_dim: 113
  encoder_type: 'lstm'
  hidden_dim: 64
  decoder_type: 'single_gaussian'
  number_gaussians: 1

# Training Setup
training:
  log_dir: "logs/prediction"  
  seed: 102
  learning_rate: 0.0001
  epochs: 100
  l2_lambda: 0.05